Repository acekyd/made-in-nigeria, pull requests merged in 2022-01, with the labels that each got.

#186 Added ExpressWebJs a NodeJS framework by Chukwuemeka Igbokwe
  README.MD
Labels: Awaiting review

#185 Add GeoIP Location and Vue Simple ACL by @victoryosayi
  README.MD
Labels: enhancement, Awaiting review

#184 Add use-global-hook and use-cookie
  README.MD
Labels: enhancement
